### ISSUE TITLE
Add Bazelisk as a potential version

### ISSUE THREAD

**Issue by strican** [andrewrothstein/ansible-bazel#3]
I'd like to be able to use Bazelisk for my builds rather than a specific version. My current use case is to use this playbook to create an agent for Buildkite. Being able to use the same agent image for multiple different versions of Bazel would be ideal, and Bazelisk allows me to achieve that.

**Comment by strican** [comment]
Actually, after taking a look at this, enough is different that it may make sense to be a separate role. I'm new to ansible, though, so I'd be interested in hearing your thoughts about it.

**Comment by andrewrothstein** [comment]
I got u started. Take a look at https://github.com/andrewrothstein/ansible-bazelisk. Kick the tires and lmk if it works for u. Always happy to accept a PR to make it more useful.

**Comment by strican** [comment]
Thank you. This seems to be working and will be helpful. I appreciate it!
