### ISSUE TITLE
question regarding java install

### ISSUE THREAD

**Issue by damianoneill** [andrewrothstein/ansible-bazel#4]
Hi @andrewrothstein is there a way to bypass the java installation as part of the bazel role?  I'm planning to use sdkman to manage all the jvms on the host.  

Thanks,
Damian.

**Comment by damianoneill** [comment]
Hi @andrewrothstein checking in to see if you have had a chance to consider this?  Thanks.

**Comment by andrewrothstein** [comment]
I published v3.0.0 of the role to the galaxy. I eliminated the explicit role dependency on my openjdk role. I also added the ability to do a no_jdk install. ur now free to use ur own strategy for installing a JDK and using this role, if u want, to install the no_jdk version of bazel with it.

**Comment by damianoneill** [comment]
Thankyou Andrew, much appreciated.
